Update GitHub Actions for linting Python and JavaScript

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,10 +1,14 @@
-name: 'Lint Code'
+name: Lint Code
 
 on:
   push:
-    branches: [master, main]
+    branches:
+      - main
+      - master
   pull_request:
-    branches: [master, main]
+    branches:
+      - main
+      - master
 
 jobs:
   lint_python:
@@ -12,48 +16,50 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v4
 
-    - name: Checkout Repository
-      uses: actions/checkout@v3
-    
-    - name: Set up Python
-      uses: actions/setup-python@v4
-      with:
-        python-version: 3.12
+      - name: Set up Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: "3.12"
 
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install flake8
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install flake8
 
-    - name: Print working directory
-      run: pwd
-
-    - name: Run Linter
-      run: |
-        pwd
-        # This command finds all Python files recursively and runs flake8 on them
-        find . -name "*.py" -exec flake8 {} +
-        echo "Linted all the python files successfully"
+      - name: Run Flake8
+        run: |
+          echo "Linting Python files..."
+          find . -type f -name "*.py" -exec flake8 {} +
+          echo "Linted all Python files successfully"
 
   lint_js:
-      name: Lint JavaScript Files
-      runs-on: ubuntu-latest
+    name: Lint JavaScript Files
+    runs-on: ubuntu-latest
 
-      steps:
+    steps:
       - name: Checkout Repository
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
 
-      - name: Install Node.js
-        uses: actions/setup-node@v3
+      - name: Set up Node.js
+        uses: actions/setup-node@v4
         with:
-          node-version: 14
+          node-version: "20"
 
       - name: Install JSHint
-        run: npm install jshint --global
+        run: npm install -g jshint
 
-      - name: Run Linter
+      - name: Run JSHint
         run: |
-          # This command finds all JavaScript files recursively and runs JSHint on them
-          find ./server/database -name "*.js" -exec jshint {} +
-          echo "Linted all the js files successfully"
+          echo "Linting JavaScript files..."
+
+          if [ -d "./server/database" ]; then
+            find ./server/database -type f -name "*.js" -exec jshint {} +
+          else
+            echo "Directory ./server/database not found"
+            exit 1
+          fi
+
+          echo "Linted all JavaScript files successfully"
